//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAITHI
    {
        public string IDTestResult { get; set; }
        public string IDStudent { get; set; }
        public Nullable<int> DiemSo { get; set; }
        public string DiemChu { get; set; }
        public string GhiChu { get; set; }
    
        public virtual SINHVIEN SINHVIEN { get; set; }
        public virtual CHAMTHI CHAMTHI { get; set; }
    }
}
