//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETBAOCAO
    {
        public string IDSubject { get; set; }
        public int Year { get; set; }
        public Nullable<int> NumberOfTest { get; set; }
        public Nullable<int> NumberOfTestResult { get; set; }
    
        public virtual BAOCAONAM REPORT { get; set; }
        public virtual MONHOC SUBJECT { get; set; }
    }
}
