//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASS()
        {
            this.TESTRESULTDETAIL = new HashSet<TESTRESULTDETAIL>();
        }
    
        public string IDClass { get; set; }
        public string IDSubject { get; set; }
        public string Username { get; set; }
        public int Semester { get; set; }
        public int Year { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTRESULTDETAIL> TESTRESULTDETAIL { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
        public virtual USER USER { get; set; }
    }
}
