//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETHI()
        {
            this.CHAMTHI = new HashSet<CHAMTHI>();
            this.CHITIETDETHI = new HashSet<CHITIETDETHI>();
        }
    
        public string IDTest { get; set; }
        public string IDSubject { get; set; }
        public Nullable<int> NamHoc { get; set; }
        public Nullable<int> HocKi { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMTHI> CHAMTHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDETHI> CHITIETDETHI { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
