//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.TESTRESULTDETAIL = new HashSet<CHAMTHI>();
        }
    
        public string IDClass { get; set; }
        public string IDSubject { get; set; }
        public string Username { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> Year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMTHI> TESTRESULTDETAIL { get; set; }
        public virtual MONHOC SUBJECT { get; set; }
        public virtual NGUOISUDUNG USER { get; set; }
    }
}
