//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDeThiEntities : DbContext
    {
        public QuanLyDeThiEntities()
            : base("name=QuanLyDeThiEntities")
        {
            Configuration.ProxyCreationEnabled = true;
            Configuration.LazyLoadingEnabled = true;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TESTRESULT> TESTRESULT { get; set; }
        public virtual DbSet<REPORT> REPORT { get; set; }
        public virtual DbSet<QUESTION> QUESTION { get; set; }
        public virtual DbSet<TESTRESULTDETAIL> TESTRESULTDETAIL { get; set; }
        public virtual DbSet<REPORTDETAIL> REPORTDETAIL { get; set; }
        public virtual DbSet<TESTDETAIL> TESTDETAIL { get; set; }
        public virtual DbSet<TEST> TEST { get; set; }
        public virtual DbSet<DIFFICULTY> DIFFICULTY { get; set; }
        public virtual DbSet<CLASS> CLASS { get; set; }
        public virtual DbSet<SUBJECT> SUBJECT { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<STUDENT> STUDENT { get; set; }
        public virtual DbSet<PRINCIPLE> PRINCIPLE { get; set; }
    }
}
