//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDeThiEntities : DbContext
    {
        public QuanLyDeThiEntities()
            : base("name=QuanLyDeThiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAITHI> TESTRESULT { get; set; }
        public virtual DbSet<BAOCAONAM> REPORT { get; set; }
        public virtual DbSet<CAUHOI> QUESTION { get; set; }
        public virtual DbSet<CHAMTHI> TESTRESULTDETAIL { get; set; }
        public virtual DbSet<CHITIETBAOCAO> REPORTDETAIL { get; set; }
        public virtual DbSet<CHITIETDETHI> TESTDETAIL { get; set; }
        public virtual DbSet<DETHI> TEST { get; set; }
        public virtual DbSet<DOKHO> DIFFICULTY { get; set; }
        public virtual DbSet<LOP> CLASS { get; set; }
        public virtual DbSet<MONHOC> SUBJECT { get; set; }
        public virtual DbSet<NGUOISUDUNG> USER { get; set; }
        public virtual DbSet<SINHVIEN> STUDENT { get; set; }
        public virtual DbSet<THAMSO> PRINCIPLE { get; set; }
    }
}
