//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDeThiEntities : DbContext
    {
        public QuanLyDeThiEntities()
            : base("name=QuanLyDeThiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAITHI> BAITHI { get; set; }
        public virtual DbSet<BAOCAONAM> BAOCAONAM { get; set; }
        public virtual DbSet<CAUHOI> CAUHOI { get; set; }
        public virtual DbSet<CHAMTHI> CHAMTHI { get; set; }
        public virtual DbSet<CHITIETBAOCAO> CHITIETBAOCAO { get; set; }
        public virtual DbSet<CHITIETDETHI> CHITIETDETHI { get; set; }
        public virtual DbSet<DETHI> DETHI { get; set; }
        public virtual DbSet<DOKHO> DOKHO { get; set; }
        public virtual DbSet<LOP> LOP { get; set; }
        public virtual DbSet<MONHOC> MONHOC { get; set; }
        public virtual DbSet<NGUOISUDUNG> NGUOISUDUNG { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIEN { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<THAMSO> THAMSO { get; set; }
    }
}
