//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINCIPLE
    {
        public int id { get; set; }
        public Nullable<int> MaxNumberOfQuestion { get; set; }
        public Nullable<int> MaxTimeForTest { get; set; }
        public Nullable<int> MinTimeForTest { get; set; }
        public Nullable<int> MaxScore { get; set; }
        public Nullable<int> MinScore { get; set; }
    }
}
