//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTRESULTDETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TESTRESULTDETAIL()
        {
            this.TESTRESULT = new HashSet<TESTRESULT>();
        }
    
        public string IDTestResult { get; set; }
        public string IDClass { get; set; }
        public string Username { get; set; }
        public string IDTest { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTRESULT> TESTRESULT { get; set; }
        public virtual CLASS CLASS { get; set; }
        public virtual TEST TEST { get; set; }
        public virtual USER USER { get; set; }
    }
}
