//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTRESULT
    {
        public string IDTestResult { get; set; }
        public string IDStudent { get; set; }
        public Nullable<int> ScoreNumber { get; set; }
        public string ScoreString { get; set; }
        public string Note { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
        public virtual TESTRESULTDETAIL TESTRESULTDETAIL { get; set; }
    }
}
