//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTDETAIL
    {
        public string IDTest { get; set; }
        public int No { get; set; }
        public int IDQuestion { get; set; }
    
        public virtual QUESTION QUESTION { get; set; }
        public virtual TEST TEST { get; set; }
    }
}
