//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEST()
        {
            this.TESTRESULTDETAIL = new HashSet<TESTRESULTDETAIL>();
            this.TESTDETAIL = new HashSet<TESTDETAIL>();
        }
    
        public string IDTest { get; set; }
        public string IDSubject { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> TimeForTest { get; set; }
        public Nullable<System.DateTime> DateOfTest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTRESULTDETAIL> TESTRESULTDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTDETAIL> TESTDETAIL { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
