//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChamThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int id { get; set; }
        public Nullable<int> SoCauToiDa { get; set; }
        public Nullable<int> ThoiLuongToiDa { get; set; }
        public Nullable<int> ThoiLuongToiThieu { get; set; }
        public Nullable<int> DiemSoToiDa { get; set; }
        public Nullable<int> DiemSoToiThieu { get; set; }
    }
}
